In [23]:
import numpy as np

### QUESTION #1

Create a 1D array and filled with 36 elements. The elements are random numbers generated from a range of values 1 to 100. 
Store the array in a variable called first_array.

In [24]:
first_array = np.random.randint(low=1, high=100, size=36)
first_array

array([71, 44,  8, 47, 35, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93, 63,
       18, 90, 44, 34, 74, 62, 14, 95, 48, 15, 72, 78, 87, 62, 40, 85, 80,
       82, 53])

### QUESTION #2

Change the dimensions with the following conditions:

a. Change the dimensions of first_array into 2D array with size 2x18

In [25]:
first_array.reshape(2, 18)

array([[71, 44,  8, 47, 35, 78, 81, 36, 50,  4,  2,  6, 54,  4, 54, 93,
        63, 18],
       [90, 44, 34, 74, 62, 14, 95, 48, 15, 72, 78, 87, 62, 40, 85, 80,
        82, 53]])

b. Change the dimensions of first_array into 3D array with size 2x6x3

In [26]:
first_array.reshape(2, 6, 3)

array([[[71, 44,  8],
        [47, 35, 78],
        [81, 36, 50],
        [ 4,  2,  6],
        [54,  4, 54],
        [93, 63, 18]],

       [[90, 44, 34],
        [74, 62, 14],
        [95, 48, 15],
        [72, 78, 87],
        [62, 40, 85],
        [80, 82, 53]]])

c. Display the maximum and minimum values along with the index.

In [27]:
print(f'Min value: {np.min(first_array)}, index {np.argmin(first_array)}')
print(f'Max value: {np.max(first_array)}, index {np.argmax(first_array)}')

Min value: 2, index 10
Max value: 95, index 24


### QUESTION #3

Create a new array from firstArray with the data taken from index 3, 5, 30, 12, 15, 8, 24, 14, 22. Reshape it into 3x3, and store in the second_array variable. Then, display the data whose value is greater than 50.

In [61]:
second_array = first_array[[3, 5, 30, 12, 15, 8, 24, 14, 22]].reshape(3, 3)
second_array[second_array > 50]

array([78, 62, 54, 93, 95, 54, 62])

### QUESTION #4

Generate 20 decimal numbers randomly and assign them to the third_array variable. Then, reshape into 4 rows and 5 columns.

In [75]:
np.random.seed(0)
third_array = np.random.rand(20).reshape(4, 5)
third_array

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

a. Find the values in the third row.

In [65]:
third_array[2]

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

b. Find the values in the fourth column.

In [66]:
third_array[:, 3]

array([0.54488318, 0.96366276, 0.92559664, 0.77815675])

c. Find the value in the 2rd row and 2nd column.

In [67]:
third_array[1, 1]

0.4375872112626925

d. Find the values in the last 3 columns

In [70]:
third_array[:, 2:]

array([[0.60276338, 0.54488318, 0.4236548 ],
       [0.891773  , 0.96366276, 0.38344152],
       [0.56804456, 0.92559664, 0.07103606],
       [0.83261985, 0.77815675, 0.87001215]])

### QUESTION #5 

Define fourth_array as np.arange(9)

In [34]:
fourth_array = np.arange(9).reshape(3, 3)
fourth_array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

a. [[1, 0, 2], [4, 3, 5], [7, 6, 8]]

In [35]:
fourth_array[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

b. [[3, 4, 5], [0, 1, 2], [6, 7, 8]]

In [36]:
fourth_array[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

c. [[2, 1, 0], [5, 4, 3], [8, 7, 6]]

In [37]:
fourth_array[:, [2, 1, 0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

### QUESTION #6

Concatenate x and y so that a new array looks like z

In [76]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
np.array([[7, 8, 9], [10, 11, 12]])

array([[ 7,  8,  9],
       [10, 11, 12]])

In [38]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=1)
z

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### QUESTION #7 

Given the x as np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10]).

a. Get numbers higher than the elements mean

In [85]:
x = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
x[x > x.mean()]

array([ 2,  5,  6, 10])

b. Get numbers equal to 2 or 10

In [82]:
x[(x==2) | (x==10)]

array([ 2, 10])

c. If an element of x is smaller than 3, replace it with 3. And if an element of x is bigger than 5, replace it with 5.

In [86]:
np.where(x < 3, 3, np.where(x > 5, 5, x))

array([3, 3, 3, 3, 5, 5, 3, 3, 3, 5])

### QUESTION #8

Given the x as np.array([1, 2, 4, 7, 0]). Calculate the difference between neighboring elements, element-wise.

In [94]:
x = np.array([1, 2, 4, 7, 0])
x[1:] - x[:-1]

array([ 1,  2,  3, -7])